name: Pull Request - Build and Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

permissions:
    contents: read

jobs:
  build_n_test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Compile Project
        run: sbt compile
      - name: Run All Tests
        run: sbt test