name: Checkita Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate SemVer App Token
        id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SEMVER_APP_ID }}
          private-key: ${{ secrets.SEMVER_APP_PKEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app_token.outputs.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec
      - run: semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
  pages: # deploy docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Checkout latest release tags
        run: |
          export LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force